language: node_js
sudo: false

node_js:
- '0.12'
- '4'
- '5'

deploy:
  provider: npm
  email: eloisant@gmail.com
  api_key:
    secure: C3fXXtk20vLty7/0+ORC0HaKHRGNdSYy8eLt2UZkXKDiBsPBfMyO3MrNASJhWgpZcjNJJBgkWmgOU/g12VrEH6CJ8BicIkOVlhLERPfCc2OfTZGyzZCBx7p1/mu0/FJ0veP5VKYvOIDyJMkwypY0KEN4MJ3RJSfjbTfRsC02SEI=
  on:
    tags: true
    all_branches: true
    repo: prismicio/javascript-kit
